# syntax=docker/dockerfile:1

FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY index.html 404.html styles.css standards.js app.js ./
COPY modules ./modules
COPY images ./images

RUN node --check app.js \
  && find modules -name "*.js" -print0 | xargs -0 -r -n 1 node --check \
  && mkdir -p /app/public \
  && cp index.html 404.html styles.css standards.js app.js /app/public/ \
  && cp -R modules images /app/public/

FROM nginx:stable-bookworm

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/public /usr/share/nginx/html

EXPOSE 80