window.FIVE_S_LEVEL_LABELS = [
  "Rất xấu (Cấp 1)",
  "Xấu (Cấp 2)",
  "Bình thường (Cấp 3)",
  "Tốt (Cấp 4)",
  "Rất tốt (Cấp 5)",
];

window.FIVE_S_STANDARDS = {
  a1: {
    "phan-loai": [
      "Không có vạch ngăn cách.",
      "Đã có vạch ngăn cách, nhưng bị mờ, đồ vật để trên đường đi bộ. Chưa chưa quy định bằng văn bản. (Basic rule)",
      "Có vạch ngăn cách đường đi bộ mới nhưng vẫn còn các vạch cũ, vết sơn cũ, bề mặt mấp mô. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Vạch cũ, vết sơn nhỏ đã được tẩy sạch và sàn phẳng.",
      "Đường dễ đi không có vật cản trở.",
    ],
    "sap-xep": [
      "Đường đi bộ lẫn với đường dành cho xe, đồ vật để lung tung.",
      "Đường đi bộ vẫn để hàng hóa nhưng có gắn thẻ thông tin trên hàng",
      "Đã phân định rõ ràng đường dành cho đi bộ & xe riêng. Không có hàng để trên đường.",
      "Duy trì tốt vạch dừng, như có kí hiệu dấu chân, có đường kí hiệu KYT trên sàn.",
      "Có biển chỉ dẫn hướng đi, có sơ đồ chỉ hướng",
    ],
    "lau-don": [
      "Đường đi bộ rất bẩn, có nhiều rác, dầu mỡ, bụi,….",
      "Đường đi bộ đã vệ sinh nhưng vẫn còn bẩn, rác..",
      "Không có rác, đường đi bộ còn chút bụi, có lịch vệ sinh.",
      "Không có bụi và vết bẩn trên lối đi bộ và trên đường vạch ngăn cách. (Border)",
      "Đường đi bộ, vạch ngăn cách, sàn nhà sạch bóng.",
    ],
  },
  a2: {
    "phan-loai": [
      "Không phân loại cốc & Vỏ bình nước hết, bình mới",
      "Phân loại vỏ bình nước hết, bình mới, cốc uống đã phân loại theo ca, nhưng chưa quy định bằng văn bản.",
      "Hiển thị rõ cốc theo ca và bình cũ/mới. Có giẻ vệ sinh. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Hoàn toàn không có đồ không cần thiết, hiển thị rõ thời gian cấp nước.",
      "Có cải tiến để giữ đúng quy định và giảm thời gian 5S",
    ],
    "sap-xep": [
      "Bình nước cũ, mới & cốc xếp lộn xộn",
      "Vật dụng và bình nước đã sắp xếp theo nhưng vẫn lộn xộn",
      "Sắp xếp bình nước theo In-out, max-min, hiển thị rõ số lượng, cốc được chia theo từng ca.",
      "Có quy định người chịu trách nhiệm, đồ vật được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Mọi thiết bị được bảo dưỡng duy trì tốt",
    ],
    "lau-don": [
      "Cây uống và sàn nhà rất bẩn, nước tràn khắp sàn….",
      "Nước chảy tràn trên sàn nhà",
      "Lau dọn theo lịch nhưng còn chút nước đọng, có khay hứng nước chống tràn",
      "Giữ gìn vệ sinh sạch sẽ, không có vết bẩn",
      "Hoạt động làm sạch được duy trì tốt, mọi vật được làm sạch.",
    ],
  },
  a3: {
    "phan-loai": [
      "Có giẻ lau, găng tay,… trong bồn",
      "Có dầu, hóa chất trong bồn. Chưa chưa quy định bằng văn bản. (Basic rule)",
      "Không có những đồ vật không cần thiết. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Có dụng cụ: tấm cọ rửa, khăn lau tay, xà phòng,…",
      "Bảo dưỡng định kỳ, giữ gìn tốt thiết bị, máy rửa mắt,….",
    ],
    "sap-xep": [
      "Không có dụng cụ vệ sinh, không dọn vệ sinh",
      "Có dụng cụ vệ sinh nhưng để lộn xộn.",
      "Dụng cụ vệ sinh sắp xếp đúng quy định, có sẵn giẻ lau để làm vệ sinh.",
      "Có quy định người chịu trách nhiệm và người quản lý, đồ vật được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Mọi thiết bị được bảo dưỡng duy trì tốt",
    ],
    "lau-don": [
      "Chậu rửa rất bẩn có dầu mỡ, rác bẩn, nước tràn khắp sàn….",
      "Nước chảy tràn trên sàn nhà",
      "Sàn nhà, thiết bị sạch sẽ, có lịch vệ sinh.",
      "Giữ gìn vệ sinh sạch sẽ, không có vết bẩn, có kế hoạch bảo dưỡng thiết bị định kỳ.",
      "Hoạt động làm sạch được duy trì tốt, mọi vật được làm sạch, sáng bóng.",
    ],
  },
  b1: {
    "phan-loai": [
      "Không phân loại, để lẫn cả những vật dụng không phải là dầu mỡ, hóa chất, dung môi.",
      "Đã phân loại nhưng chưa có quy định văn bản. Còn vật không cần thiết như găng tay, giẻ lau…..",
      "Chỉ có dầu, hóa chất cần cho sử dụng. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Có người chịu trách nhiệm, lượng lưu trữ, bảng hiển thị chủng loại dầu, hóa chất.",
      "Có cải tiến để giảm lượng lưu kho dầu, hóa chất (stock)",
    ],
    "sap-xep": [
      "Dầu mỡ, hóa chất để lẫn lộn với nhau",
      "Dầu, hóa chất được đặt ở đúng nơi quy định nhưng vẫn ngổn ngang",
      "Được sắp xếp theo (5 Fix). Có giá và khay hứng dầu, hóa chất. \"First in-first out\".",
      "Đặt theo thứ tự từng loại riêng, được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Có sự quản lý chủng loại, lượng dầu, hóa chất cần dùng",
    ],
    "lau-don": [
      "Vị trí để và xung quanh có dầu, hóa chất, có nhiều bụi bẩn trên sàn và giá hàng",
      "Khu vực xung quanh nơi để dầu, hóa chất bẩn",
      "Có sẵn dụng cụ (giẻ lau,…) để vệ sinh khi cần. Giá và khay hứng dầu, hóa chất còn chút bụi, có lịch vệ sinh.",
      "Luôn lau dọn sạch và giữ sạch sẽ.",
      "Có cách phòng ngừa để không làm tràn tràn, đổ dầu",
    ],
  },
  b2: {
    "phan-loai": [
      "Không phân loại, để lẫn lộn vật cần và không cần dùng",
      "Hàng tốt và hàng lỗi để gần nhau không có ngăn cách và ký hiệu. Chưa chưa quy định bằng văn bản. (Basic rule)",
      "Nơi để hàng tốt và hàng lỗi được tách riêng. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Hàng lỗi được đánh dấu màu đỏ và đặt theo thứ tự",
      "Hàng tốt được đặt theo đúng thứ tự",
    ],
    "sap-xep": [
      "Không có kanban cho hàng hóa.",
      "Có Kanban nhưng không để cùng hàng hóa",
      "Hàng hóa và Kanban được sắp xết theo thứ tự (5 Fix). Thực hiện \"vào trước - ra trước/First in-first out\"",
      "Sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng. Thực hiện Min - max stock.",
      "Thực hiện quản lý bằng Kanban, quản lý Min - max stock.",
    ],
    "lau-don": [
      "Trên hàng hóa, Kanban, giá để & sàn nhà bám nhiều bụi bẩn, dầu mỡ.",
      "Bảng quản lý, Kanban & Sàn nhà bụi bẩn, có dầu mỡ…",
      "Đã vệ sinh theo lịch nhưng bảng quản lý & kanban còn chút bẩn.",
      "Thực hiện làm sạch định kỳ, có PIC.",
      "Có cách thức để ngăn ngừa bụi bám vào hàng hóa",
    ],
  },
  b3: {
    "phan-loai": [
      "Để hàng hóa, vật liệu không rõ mục đích sử dụng, không quy định vị trí.",
      "Đã quy định vị trí cho vật liệu có thể sử dụng được và không sử dụng được, nhưng chưa có Basic rule",
      "Chỉ để những vật có thể dùng được. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Chỉ để những vật tư, vật liệu cần thiết.",
      "Chỉ để những vật cần thiết và đặt đúng thứ tự",
    ],
    "sap-xep": [
      "Để hàng hóa lộn xộn",
      "Đã sắp xếp hàng hóa nhưng vẫn lộn xộn.",
      "Có Kanban và hàng hóa được sắp xết theo thứ tự 5 Fix. Hiển thị ngày hết hiệu lực và đặt gần vật liệu.",
      "Tên vật tư, vật liệu với giá hàng được hiển thị đúng, được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Quản lý theo loại và lượng, thời điểm đặt hàng",
    ],
    "lau-don": [
      "Giá hàng, vật tư, vật liệu, dụng cụ bám nhiều bụi, dầu mỡ….",
      "Đã vệ sinh giá để hàng & kanban còn bẩn bụi, dầu mỡ…",
      "Làm vệ sinh theo lịch nhưng còn chút bẩn.",
      "Luôn dọn dẹp và giữ sạch sẽ",
      "Có cách ngăn ngừa bụi không bám vào giá kệ, vật tư",
    ],
  },
  c1: {
    "phan-loai": [
      "Không phân loại rõ đồ vật. Còn đồ cá nhân & đồ không cần thiết",
      "Đã phân loại nhưng vẫn còn đồ vật không cần thiết & chưa có Basic rule",
      "Chỉ để những vật cần thiết. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Nơi đặt để được chỉ định rõ và phân loại theo thứ tự.",
      "Có cải tiến để giữ đồ vật đúng quy định",
    ],
    "sap-xep": [
      "Để đồ vật ngổn ngang",
      "Đã sắp xếp còn chút lộn xộn.",
      "Được sắp xếp theo thứ tự (5 Fix).",
      "Những vật cần dùng được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Có hiển thị rõ ràng và giữ gọn gàng",
    ],
    "lau-don": [
      "Có nhiều bụi bẩn, rác, dầu mỡ….",
      "Đã vệ sinh nhưng vẫn còn bẩn, bui.",
      "Có kế hoạch làm vệ sinh nhưng vẫn còn chút bụi.",
      "Lau dọn được thực hiện theo kế hoạch và sạch sẽ.",
      "Có cái tiến để sàn nhà lúc nào cũng sạch sẽ, sáng bóng.",
    ],
  },
  c2: {
    "phan-loai": [
      "Thiết bị đi kèm (tấm cover máy) bị tháo ra và vứt lại.",
      "Bulong của máy tháo ra chưa lắp lại. Bảng điều khiển hiển thị nhưng không rõ, còn vật không cần thiết.(Giẻ lau, găng tay) chưa có Basic rule",
      "Thiết bị đi kèm tháo ra được để đúng quy định. Bảng điểu khiển hiển thị rõ, (Tên, Tiêu chuẩn..)Có quy định phê duyệt. (basic rule)",
      "Chỉ có thiết bị và hướng dẫn vận hành, check sheet theo dõi.",
      "Có theo dõi ngày tháng bảo dưỡng thiết bị định kỳ.",
    ],
    "sap-xep": [
      "Dây điện, dây khí, ống nước lộn xộn trên sàn.",
      "Vẫn còn dây dẫn, ống dẫn tạm thời trên máy. Dây điện, ống khí, nước đã buộc nhưng còn lộn xộn.",
      "Dây, ống dùng trong thời gian ngắn được bó gọn để cùng nhau. Dây điện, ống khí, nước được bó gọn theo quy định. (5 Fix)",
      "Dây điện, ống khí, ống nước được cố định gọn gàng, thuận tiện cho thao tác",
      "Các loại dây được đặt trong ống gọn gàng,",
    ],
    "lau-don": [
      "Rò nước, rò dầu, rò khí, máy bám nhiều bụi bẩn, dầu mỡ.",
      "Đã lau dọn hết dầu mỡ nhưng thiết bị, máy móc vẫn còn bụi, bẩn.",
      "Lau dọn theo kế hoạch nhưng vẫn còn chút bụi.",
      "Máy móc, thiết bị luôn sạch sẽ, có kế hoạch bảo dưỡng thiết bị định kỳ.",
      "Có cải tiến để luôn duy trì điều kiện sạch sẽ.",
    ],
  },
  c3: {
    "phan-loai": [
      "Không quy định vị trí, có vật dụng cá nhân, vật không cần thiết",
      "Đã quy định vị trí, như vẫn còn vật không cần thiết. chưa có Basic rule",
      "Chỉ có những vật cần thiết. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Mục đích sử dụng của đồ vật cần thiết được hiển thị rõ.",
      "Có theo dõi ngày tháng bảo dưỡng thiết bị định kỳ.",
    ],
    "sap-xep": [
      "Đồ vật & dụng cụ ngổn ngang",
      "Dụng cụ sau khi dùng xong chưa được sắp xếp.",
      "Đặt để vật theo đúng thứ tự quy định, có hiển thị rõ theo (5 Fix)",
      "Đặt để gọn gàng, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Được duy trì sắp xếp theo quy định.",
    ],
    "lau-don": [
      "Có nhiều bụi bẩn, rác, dầu mỡ….",
      "Có lau dọn nhưng vẫn còn bẩn bụi, dính chút dầu mỡ.",
      "Có tần suất vệ sinh nhưng còn chút bẩn.",
      "Giữ gìn vệ sinh sạch sẽ, không có vất bẩn.",
      "Có cải tiến để luôn duy trì điều kiện sạch sẽ.",
    ],
  },
  c4: {
    "phan-loai": [
      "Không phân loại, có vật dụng cá nhân & vật không cần thiết.",
      "Để lẫn cả đồ đã hỏng và đồ không dùng được với đồ cần thiết. chưa có Basic rule",
      "Chỉ có đồ vật cần thiết, có danh sách đính kèm. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Những đồ cần thiết luôn đúng quy định",
      "Hiển thị rõ nơi cần dùng đồ vật (sử dụng cho công đoạn nào,…)",
    ],
    "sap-xep": [
      "Đồ vật để lộn xộn không nhận biết được.",
      "Có quy định chỗ để rõ ràng nhưng vẫn để ngổn ngang",
      "Sắp xếp theo quy định vị trí rõ ràng, theo (5 Fix)",
      "Được sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng. Có thẻ mượn để ngăn ngừa mất dụng cụ.",
      "Ngay lập tức có thể lấy ngay những dụng cụ thích hợp",
    ],
    "lau-don": [
      "Có những vết gỉ sét, nhiều bụi bẩn, dầu mỡ.",
      "Đã vệ sinh nhưng còn bụi bẩn, dầu mỡ.",
      "Có tần suất vệ sinh, còn chút bụi.",
      "Bảo quản, giữ gìn và vệ sinh tốt",
      "Sẵn sàng có thể sử dụng được ngay",
    ],
  },
  c5: {
    "phan-loai": [
      "Không quy định rõ khu vực hiển thị, treo, dán tài liệu, có những tài liệu cũ, lỗi thời.",
      "Đã quy định vị trí, vẫn còn tài liệu đã hết hạn. chưa có Basic rule",
      "Chỉ hiển thị các tài liệu cần thiết. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Tài liệu được phân chia đúng loại.",
      "Luôn duy trì được ở tình trạng tốt, luôn đúng thời gian quy định và được lưu giữ.",
    ],
    "sap-xep": [
      "Tài liệu chồng chất lên rất khó nhìn, khó đọc.",
      "Dán/treo tài liệu thẳng theo hàng lối nhưng chưa có border & dán không chắc.",
      "Để tài liệu theo đúng thứ tự & theo đúng vị trí border.",
      "Vị trí sắp xếp thẳng hàng, ngăn nắp thuận tiện cho người sử dụng.",
      "Tài liệu lấy đi và mang trả lại dễ dàng, thuận tiện cho ghi chép.",
    ],
    "lau-don": [
      "Bảng, màn hình andon rất bẩn, bụị, có bám dầu mỡ.",
      "Đã lau dọn nhưng bảng và xung quanh còn bẩn",
      "Được lau dọn theo kế hoạch nhưng vẫn còn hơi bụi.",
      "Có PIC và tần xuất lau dọn được duy trì sạch sẽ.",
      "Có cải tiến để duy trì tình trạng lúc nào cũng sạch sẽ.",
    ],
  },
  d1: {
    "phan-loai": [
      "Không quy định vị trí, không rõ vật cần hay không cần và đồ cá nhân.",
      "Có quy định vị trí nhưng vẫn còn vật không cần thiết & cá nhân (Găng tay bẩn, mũ…) chưa có Basic rule",
      "Vật dụng cần thiết để gọn gàng. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Tài liệu hiển thị, bàn, ghế được phân loại rõ.",
      "Hoàn toàn không có vật không cần thiết",
    ],
    "sap-xep": [
      "Không sắp xếp vật dụng tại khu nghỉ. (Bàn, ghế, check sheet, dụng cụ, bánh kẹo,…)",
      "Đã sắp xếp nhưng vẫn lộn xộn. (Bàn, ghế, check sheet, báo, sữa, nước…)",
      "Đặt để đúng vị trí quy định.",
      "Sắp xếp đúng vị trí quy định, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Có cải tiến để luôn sắp xếp đúng quy định",
    ],
    "lau-don": [
      "Tường, sàn nhà, bàn ghế rất bẩn.",
      "Bàn ghế bẩn. (Có vết trà, cà phê,…)",
      "Có tấn xuất vệ sinh nhưng còn chút bụi. (Kính, tường, giá kệ..)",
      "Có PIC (Tổ viên) & Quy định luân chuyển 4S",
      "Thường xuyên lau dọn sạch sẽ, sáng bóng.",
    ],
  },
  d2: {
    "phan-loai": [
      "Không nhận biết được đồ cần thiết và không cần thiết. Có đồ cá nhân.",
      "Quy định rõ vật cần thiết & không cần. Tài liệu hiển thị và tài liệu quản lý không được phân loại. (chưa có basic rule).",
      "Phân loại rõ tài liệu & thiết bị. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Không có đồ không cần thiết, hiển thị rõ mục đính của từng tài liệu & thiết bị.",
      "Chỉ để những vật cần thiết và phân đúng chủng loại.",
    ],
    "sap-xep": [
      "Tài liệu chất đống lộn xộn.",
      "Để tài liệu để đúng nơi quy định nhưng vẫn lộn xộn.",
      "Thiết bị & tài liệu sắp xếp theo thứ tự.",
      "Tài liệu được gán nhãn, chia file, sắp xếp, dễ thấy, dễ lấy, thuận tiện cho người sử dụng.",
      "Tài liệu khi cần là lấy được ngay.",
    ],
    "lau-don": [
      "Bàn, ghế, tài liệu, điện thoại và máy tính và mũ của GL rất bẩn",
      "Điện thoại và máy tính bẩn.",
      "Có PIC & lịch lau dọn. Làm 4S nhưng vẫn còn chút bẩn.",
      "Thực hiện làm 4S theo đúng thời giờ quy định",
      "Khu vực xung quanh bàn của GL luôn sạch sẽ",
    ],
  },
  d3: {
    "phan-loai": [
      "Có rất nhiều loại tài liệu, không phân loại.",
      "Đã phân loại tài liệu nhưng vẫn có đồ không cần thiết (Tài liệu tạm thời, File trống…) chưa có Basic rule",
      "Phân loại rõ tài liệu cần và không cần trên giá. Có quy định bằng văn bản đã phê duyệt. (basic rule)",
      "Chỉ có tài liệu cần thiết, rõ mục đích sử dụng",
      "Có Kaizen để giữ đúng quy định.",
    ],
    "sap-xep": [
      "Không nhận biết vị trí đặt để tài liệu.",
      "Có tiêu đề cho tài liệu, sắp xếp còn lộn xộn.",
      "Có tiêu đề, nhãn cho giá kệ, tài liệu. Sắp xếp theo thứ tự 5 Fix",
      "Tài liệu được phân theo nhóm, sắp xếp đúng vị trí quy định, dễ thấy, dễ lấy, thuận tiện cho người sử dụng. Có thẻ mượn.",
      "Tư liệu còn hay mất chỉ cần nhìn qua là biết được",
    ],
    "lau-don": [
      "Giá kệ, tủ tài liệu quá bẩn, bụi, dầu…",
      "Giá kệ, tủ tài liệu bẩn",
      "Đã lau dọn theo kế hoạch nhưng vẫn còn chút bụi.",
      "Có quy định luân chuyển 4S",
      "Giá kệ, cabinet lúc nào cũng sạch sẽ",
    ],
  },
  e1: {
    diem: [
      "Hoàn toàn không biết đến 5S",
      "Chỉ hiểu 5S là liên quan đến làm vệ sinh",
      "Tổ viên hiểu rằng 5S là nền tảng của sự an toàn trong công việc.",
      "Bất cứ Tổ viên nào cũng trả lời được chính xác ý nghĩa của 5S và thực hiện được 5S",
      "Tổ viên có thể chỉ ra được điểm cần kaizen, thực hiện được 4S, và đưa ra ý kiến đóng góp, lời khuyên cho đồng nghiệp được.",
    ],
  },
  e2: {
    diem: [
      "Người quản lý không quan tâm đến 5S (Không rõ hoạt động của Line mình, không có kế hoạch khắc phục vấn đề. Bảng không cập nhật….)",
      "Chỉ chỉ đạo 5S chung chung (Có kế hoạch nhưng không thực hiện đúng hạn định…)",
      "Kế hoạch 5S chỉ rõ khi nào/ai/ở đâu và thiết lập hệ thống 5S",
      "Chỉ đạo thực hiện 5S theo PDCA, dựa trên sơ đồ 5S hoặc luân chuyển công việc, GL đưa ra định hướng về hoạt động 5S của Line.",
      "Ý thức 5S của member rất cao, dù không có chỉ đạo thì vẫn thực hiện và tuân thủ nghiêm ngặt",
    ],
  },
};
